#!/bin/bash
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec1-intro-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec1-intro.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec2-relational-data-model-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec2-relational-data-model.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec3-sql-basics-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec3-sql-basics.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec4-sql-joins-aggregates-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec4-sql-joins-aggregates.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec5-sql-aggregates-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec5-sql-aggregates.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec6-subqueries-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec6-subqueries.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec7-sql-wrapup-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec7-sql-wrapup.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec8-datalog-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec8-datalog.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec9-more-datalog-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec9-more-datalog.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec10-ra-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec10-ra.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec11-more-ra-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec11-more-ra.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec12-nosql-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec12-nosql.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec13-json-sqlpp-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec13-json-sqlpp.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec14-sqlpp-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec14-sqlpp.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec15-sqlpp-wrapup-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec15-sqlpp-wrapup.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec16-query-eval-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec16-query-eval.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec17-mr-spark-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec17-mr-spark.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec18-spark-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec18-spark.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec19-er-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec19-er.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec20-design-theory-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec20-design-theory.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec21-bcnf-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec21-bcnf.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec22-txns-intro-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec22-txns-intro.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec23-more-txns-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec23-more-txns.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec24-txns-impl-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec24-txns-impl.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec25-indexes-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec25-indexes.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec26-more-index-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec26-more-index.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec27-operator-costs-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec27-operator-costs.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec28-query-optimization-6up.pdf
wget https://courses.cs.washington.edu/courses/cse414/18sp/lectures/lec28-query-optimization.pdf
